### ISSUE TITLE
Bug: "Add grant" in admin tool has no effect on context listing in "submission"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#1]
Testserver: 
https://dev.inge.mpdl.mpg.de/admintool/users
https://dev.inge.mpdl.mpg.de/pubman/faces/SubmissionPage.jsp
Browser: ff 
Version/test date: 26.10.2017
User: roland

Actions: add context to user

- create context (in this case ctx_3003547)
- search user (Catherina Hofmann) -> select role -> select created context from dropdown menue -> "add" -> context displayed in "add grants" -> "add grants" -> context listed correctly in "grants"
- added several contexts to user
- log in dev-inge -> start page -> Submission -> full/easy -> only "PubMan Test Collection" and "Test_Context_Simple" are displayed

Observation:  -> new contexts are not displayed in view "start/start submission/Collections"

This might be an older problem, since according to my grants there should have been displayed "MPG YearBook" as well.

If i add context "PubMan Test collection" to another user, user is able to work with this collection.

Expected Result: All contexts I added to user are displayed in "submission"

**Comment by wilhelmfrank** [comment]
WON'T FIX! this is possibly a bug in pubman, but not in the admin tool.

**Comment by hofmannc** [comment]
update: type "Pubman" missing for the recently created contexts 
![grafik](https://user-images.githubusercontent.com/14921701/33545216-b1b3e5ec-d8dd-11e7-979d-f32b0a127fa2.png)

**Comment by wilhelmfrank** [comment]
should be ok now, since PubMan currently doesn't check the type anymore.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland
result: ok
