### ISSUE TITLE
Create OU: "Return" deletes list items of "alternative names", "descriptions" and "identifiers"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#10]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 06.11.2017
User: roland

precondition: 
start page -> OU -> "+" -> enter several valid alternative names, descriptions and identifiers by ">>" 

Action: 
-> enter valid alternative name -> "return"

Observation: earlier entered values are deleted by return

Expected result: Hitting "return" has either 
- no effect or 
- acts as alternative to ">>" and adds value to list of alternative names

**Comment by wilhelmfrank** [comment]
input type was submit. changed to button. FIXED

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland
ok
