### ISSUE TITLE
Edit OU: Add alternative names, descriptions and identifiers not always possible 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#11]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 06.11.2017
User: roland

Action:
start page -> OU -> "+" -> enter parent id and name -> "save"
-> search OU in List -> open -> enter valid value to "alternative name" -> ">>" 

Observation 1: Add value not possible for "alternative names, descriptions and identifiers" BUT adding "Platzhalter" during creation process makes it possible to add list items:

start page -> OU -> "+" -> enter parent id and name -> add at least one list item for  "alternative names, descriptions and identifiers" -> "save"
-> search OU in List -> open -> enter valid value to "alternative name" and "Description" -> ">>" -> Values are added, list BUT

Observation 2: 
 -> enter valid value to "identifier" -> ">>" -> Value is added, but with repeating the action, no new list items are created -> only content replaced
-> to save each list item, it is necessary to ->"save" each time after creation of new list item 
This is not necessary for the two other categories

Observation 3: Edit e.g. "alternative names" -> delete all entries of the list 
-> Once I delete all items of the list, it is not possible to create new ones.

**Comment by wilhelmfrank** [comment]
Observation 1: if lists are empty, they don't exist in Json representation. FIXED
Observation 2: checking array for existing objects did not work. FIXED
Observation 3: same as 1. FIXED

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

Test result:.

1: ok
2: ok
3: ok
