### ISSUE TITLE
Sometimes the display of alternative names, descriptions and identifiers differ in different borwsers

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#12]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/
Browser: ff/chr
Version/test date: 06.11.2017
User: roland

OU example: https://dev.inge.mpdl.mpg.de/admintool/organization/ou_3003558

Action:
open ff -> create OU -> add descriptions -> "save" all entries -> add some more items -> "save"

open chr -> open earlier created OU -> 

Observation1 : -> latest entries (since last "save") are not displayed in Chrome

Then I "changed the direction":
-> saved new items in Chrome 
-> log in ff -> open OU ->

Observation 2:
- all items I created ealier in ff are not available anymore (the items which were not displayed in Chrome).
- The items I just created in Chrome are displayed

I don't know why at first it was possible to create items in FF which are also displayed in Chrome and then suddenly not anymore. I could not reproduce this for other OUs so far.

**Comment by wilhelmfrank** [comment]
WON'T FIX! cannot reproduce.

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

ok, not reproducible anymore
