### ISSUE TITLE
Missing validation for wrong handling of "Add grants"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#13]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/
Browser: ff
Version/test date: 06.11.2017
User: roland

Action:
start page -> users -> select existing user from list -> "Add grants" -> select role and context -> "add grants" 

Observation: wrong message comes up: "added Grants to user" is displayed, although grant not added

Expected result: Since I left out step "add", I did not add grant -> user should be informed correctly

**Comment by wilhelmfrank** [comment]
FIXED! if no grant is selected, an appropriate message will be displayed.

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland
ok
