### ISSUE TITLE
Add same grant twice is possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#14]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/
Browser: ff
Version/test date: 06.11.2017
User: roland

Action: add same grant twice
select user -> "add grants"  -> select role and context twice:
![grafik](https://user-images.githubusercontent.com/14921701/32617075-55d30ee6-c574-11e7-8df7-e1154ce79c7e.png)
->"add grants" 
Observation: -> message "added grants to user" and items added to grants list

--> remove both grants at once not possible 
select "x" of both items -> "remove grants" -> 
![grafik](https://user-images.githubusercontent.com/14921701/32617323-ffed6d18-c574-11e7-9817-26a9fb172c98.png)

Expected result: no possibility to add same grant twice for one user

**Comment by wilhelmfrank** [comment]
FIXED! now the same grant can be added only once. (same applies for removal).

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland
