### ISSUE TITLE
Enhancement: Make "add grant" only possible for contexts with status "opened"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#15]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

Current situation: at the moment it is possible to add grants for context with status "created" and user thinks the grant is added sucessfully although only contexts with status "opened" should be able to be added to user's grants.

Expected situation: 
user is not able to select grant with other status as "opened" or 
user gets an information about the current state of the context and is informed that due to this reason the action is not completed. (or will be completed as soon as context gets "opened"?)

**Comment by wilhelmfrank** [comment]
FIXED! only open contexts will be available to select from, as well as only open OUs will be available to select from inside user and context detail pages.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.6
Test date: 19.07.2018
User: roland
result: ok
