### ISSUE TITLE
"Alternative name"/ "Description" / "Identifier": add two empty fields possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#16]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

Actions: 
start page -> OU -> "+" -> enter parent id and name ->  "alternative name"  -> ">>" ->

Observation: ->  empty value field added and just one time repeatable 
![grafik](https://user-images.githubusercontent.com/14921701/33547384-39a8e9e2-d8e4-11e7-8e90-9d20e80a4097.png)

same for "Description" and "Identifier"

also all migrated OUs with no "alternative name"/ "Description" / "Identifier" display one or two empty fields by default

**Comment by wilhelmfrank** [comment]
FIXED!

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.6
Test date: 19.07.2018
User: roland
result: ok
