### ISSUE TITLE
Create OU: Layout issue with adding long text for "identifier"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#17]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

Actions: create ou -> add long text for identifier -> 

![grafik](https://user-images.githubusercontent.com/14921701/33547884-c873d744-d8e5-11e7-850a-2a32b280d111.png)

sometimes  for "alternative names" as well, but not always reproducible 
https://dev.inge.mpdl.mpg.de/admintool/organization/ou_3003558
![grafik](https://user-images.githubusercontent.com/14921701/33548567-d816310e-d8e7-11e7-9d30-272a59a0677a.png)

**Comment by wilhelmfrank** [comment]
FIXED! adding additional "row" container

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.6
Test date: 19.07.2018
User: roland
result: ok
