### ISSUE TITLE
OU "External Organisations": "More" not displayed after clicking "More" of MPG-OU

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#18]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

Actions: start page -> "OUs" -> click on "more" of a OU -> childs are displayed -> "External Organizations" ->  "more" buttons of these OUs are not displayed 

Solution:  "Max Planck Society" -> "Less" -> "external Organizations" -> all "more" buttons are displayed again

**Comment by wilhelmfrank** [comment]
FIXED!

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok
