### ISSUE TITLE
Enhancement: User should only get views displayed he is able to work on

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#2]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 26.10.2017
User: not logged in

Observation: currently, if user is not logged in, he is not allowed to search for users or edit OUs or contexts. But user gets search forms and edit forms and if he searches or edits, he gets an error message sying he is not allowed to do so.

Expected Result: If user is not allowed to search or edit he should not see the forms

**Comment by wilhelmfrank** [comment]
FIXED! blocked all editable pages for anonymous users.

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: not logged in/regular user

Re-test: ok for not logged in user.
BUT 
1. if I enter with regular user: since he is only allowed to see his own form , but has no grants to change something, I would remove the "action buttons" or display the information in a non editable form.
2.And for the other pages he gets the same notification as not logged in user "This site is almost useless without authentication ..."  I would change it to something like "you don't have adequate grants for this action"

**Comment by wilhelmfrank** [comment]
FIXED! deactivated all relevant buttons and adjusted appropriate messages.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland
result: ok
