### ISSUE TITLE
Context: issues if no oU selected in "create process"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#20]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/
Browser: ff
Version/test date: 13.12.2017
User: roland

Actions: 
statr page -> "contexts" -> "+" -> enter name -> "save" -> "Context Administration" -> search context -> 
1. Genres are missing 
2."open" control only small window (but working correctly)
3. Organization is not selectable

![grafik](https://user-images.githubusercontent.com/14921701/33929954-93eb8a00-dfeb-11e7-8f1c-71845bb23d14.png)

**Comment by wilhelmfrank** [comment]
FIXED!

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland
result: ok
