### ISSUE TITLE
Enhancement: Make title of forms consistent

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#21]
Testserver: https://dev.inge.mpdl.mpg.de/admintool/
Test version: version: 0.9.40
Browser: ff
Version/test date: 14.12.2017
User: roland

Current situation: Forms for new user and new context are labeled with "new ...". OU has no label.

Expected situation: "new ou" displayed in form header for OU

**Comment by wilhelmfrank** [comment]
FIXED!

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland
result: ok
