### ISSUE TITLE
OU cannot be created

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#23]
Testserver: https://dev.inge.mpdl.mpg.de/admintool/
Test version: version: 0.10.1
Browser: ff 
Version/test date: 07.02.2018
User: roland

Actions: start page -> menue "OU" -> "+" -> "parent ID" -> "ou_persistent13" -> "name" -> enter valid name -> "save"
Obderation: error message
![grafik](https://user-images.githubusercontent.com/14921701/35914549-e64a6cfa-0c03-11e8-89f0-b780615c178e.png)

**Comment by wilhelmfrank** [comment]
FIXED! in version 0.10.2
