### ISSUE TITLE
search user with " throws error message

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#27]
Testserver: https://dev.inge.mpdl.mpg.de/admintool/
Test version: version: 0.10.2
Browser: ff
Version/test date: 21.02.2018
User: admin

Actions:
User Administration -> enter " "test depositor" "  in search field ->
![grafik](https://user-images.githubusercontent.com/14921701/36483211-ce7e8454-1715-11e8-87ef-12931d44c7d1.png)

but search is actually sucessful.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland
result:  still reproducible

**Comment by wilhelmfrank** [comment]
fixed in 1.0.6
its now possible to search with or without quotes

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok
