### ISSUE TITLE
Elements created by automated tests are closed and not correctly handeled

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#29]
Testserver: https://qa.inge.mpdl.mpg.de/admintool/
Test version: version: 0.10.4
Browser: ff
Version/test date: 24.05.2018
User: admin

OUs: click on OU -> "400, ERROR [object Object]"
search context -> click on context in autosuggest -> "EmptyError: no elements in sequence"
add closed context to user -> "400, ERROR [object Object]"

expected result: no error messaged but information the element is closed and therefore not available anymore

**Comment by wilhelmfrank** [comment]
This behaviour is caused by inconsistent data on the qa server. The database and the related indices are not in sync.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok, OUs are not available anymore
