### ISSUE TITLE
Selection for context workflow disappears 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#30]
Testserver: https://qa.inge.mpdl.mpg.de/admintool/
Test version: version: 0.10.4
Browser: ff
Version/test date: 24.05.2018
User: admin

Actions:
create context -> select workflow -> "save" -> context overview -> go back to just created item -> 

Observation: selection is not displayed anymore, but functionality semms not to be affected.
Earlier created contexts display workflow correctly.

**Comment by wilhelmfrank** [comment]
this is not related to the admin tool. The WORJFLOW was not stored by INGe. Should be fixed by now.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok
