### ISSUE TITLE
Create User or context --> Authorization exception

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#32]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Test date: 10.07.2018
User: roland
result: ok

Actions: log in roland -> "Users" -> "+" ->
Observation: ![grafik](https://user-images.githubusercontent.com/14921701/42498209-dcac0ac8-842b-11e8-9849-98e2a7eec274.png)

and no organization selectable

Expected Result: roland creates user and contexts

**Comment by wilhelmfrank** [comment]
this is caused by the inaccessibility of ES outside the MPDL. Will be resolved in version 1.0.6

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok
