### ISSUE TITLE
User cannot change/reset password

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#34]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: chofmann

Precondition: deleted browser cache
Actions: log in -> Users -> user form ""chofmann" displayed -> password -> "change" 

Observation: Error 400
![grafik](https://user-images.githubusercontent.com/14921701/42875513-3f6e4c62-8a84-11e8-9ff0-ec0bc2d6dd28.png)

Expected Result: a default user is able to change (or reset) password.

**Comment by wilhelmfrank** [comment]
fixed in version 1.0.6

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: ok
