### ISSUE TITLE
Make user profiles and contexts available for external institutes  

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#36]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.5
Test date: 18.07.2018
User: roland

Current situation:
It is not possible to connect an external institute with a user profile or a context.

Expected result according to PubMan Meting of 19.07.2018: 
It should be possible to create users and contexts for external institutes

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland
result: NOK -> external institutes are not available for "new context". "New user" ok.

**Comment by wilhelmfrank** [comment]
fixed in version 1.0.8

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.8
Test date: 24.07.2018
User: roland
result: ok
