### ISSUE TITLE
wrong error message while creating new user incorrectly

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#39]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.7
Test date: 19.07.2018
User: roland

Actions:
start page -> "users" -> "+" -> "save" -> error message "userid MUST NOT be new user" -> change login name to -> "new mm" -> "save" -> "name MUST NOT be empty"

Observation1: correct error message should be "name must not have space"

-> "change loginname to newmm" ->

Observation2: error message stays "name MUST NOT be empty"

repeat action beginning with login name "newu" -> "name MUST NOT be empty"

Observation3: correct error message should be "name must have at least..."

-> "change loginname to new mm" ->

Observation2: error message stays "name MUST NOT be empty"

Expected Result: error message adapts to error

**Comment by wilhelmfrank** [comment]
fixed in 1.0.8

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.8
Test date: 24.07.2018
User: roland
result: ok, but enhancement: 
"loginname MUST NOT be new <something>"  -> better: "must not contain space" or something like that

**Comment by wilhelmfrank** [comment]
changed message to "loginname MUST NOT contain spaces"

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
