### ISSUE TITLE
Enhancement: change navigation bar to non-transparent display

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#4]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 26.10.2017
User: roland

Observation: Currently, navigation bar is transparent -> if user scrolls down, form overlaps navigation bar
![grafik](https://user-images.githubusercontent.com/14921701/32053628-2fd41cbc-ba5c-11e7-8e14-9a09d4f9861e.png)

**Comment by wilhelmfrank** [comment]
FIXED

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland
ok
