### ISSUE TITLE
Context name in an user's grant list

### ISSUE THREAD

**Issue by NTaller** [MPDL/PubManAdmin#40]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Opera 54.0
Tested version: 1.0.7
Test date: 20.07.2018
User: roland

It would be nice if the name of the context is displayed in the user's grand list.
For example:
Depositor     Publications of the Max Planck Digital Library      ctx_1600138

In the current version the context-name ist visible using a mouse over on the id..

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.8
Test date: 24.07.2018
User: roland
result: ok

**Comment by hofmannc** [comment]
@NTaller please close if ok for you

**Comment by NTaller** [comment]
The result is very nice. Thanks!
