### ISSUE TITLE
Should it be possible to use same name for OUs and contexts more than once?

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#42]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.8
Test date: 24.07.2018
User: roland

Actions: create OU -> enter "newou" -> select "ou_persistent13" -> "save" -> repeat action
search for "newou" -> two entries displayed
Observation: It is possible to create two identical OUs and contexts.
Question: Should that be possible?

**Comment by wilhelmfrank** [comment]
according to MB this is the intentional behavior.
