### ISSUE TITLE
Layout: Role not completely displayed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#43]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.10
Test date: 01.08.2018
User: roland

Actions: add grants 
Observation:
![grafik](https://user-images.githubusercontent.com/14921701/43515330-7e23657e-9582-11e8-93cc-91753cf08696.png)

**Comment by wilhelmfrank** [comment]
fixed in 1.2.1

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
