### ISSUE TITLE
Create OU: "identifier", "descriptions" and "alternative names" are not saved

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#50]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Actions: create OU -> save -> add values for "identifier", "descriptions" and "alternative names" -> save
Observation: values are not saved, while "adress, country, sratr and end date are saved
same observation if values are added with the creation process

2. observation: Status "open" -> values are still not saved with "415, ERROR: {"timestamp":"2018-09-10T10:13:59.942","status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'text/plain;charset=UTF-8' not supported"}"

Expected Result: values are saved

**Comment by wilhelmfrank** [comment]
cannot reproduce!
