### ISSUE TITLE
Roland is not allowed to search users and create users

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#51]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland
Actions -> search user -> "no  token, no users!" 
create user -> form is displayed but not allowed to save

Same observation for create context -> "415, ERROR: {"timestamp":"2018-09-10T10:08:36.467","status":415,"error":"Unsupported Media Type","exception":"org.springframework.web.HttpMediaTypeNotSupportedException","message":"Content type 'text/plain;charset=UTF-8' not supported"}"

search context is possible

**Comment by hofmannc** [comment]
after deleting cookies ok

**Comment by wilhelmfrank** [comment]
does not work as expected!!!!

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok - so far, the issue did not come up again
