### ISSUE TITLE
Change OU of deactivated user possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#52]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Actions: search active user -> "deactivate" -> change OU 
Observation: Changing OU for deactivated user possible
Expected Result: Must not be possible according to requirements

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok -> no "change OU" available anymore if user deactivated
