### ISSUE TITLE
User Profile: Changes OU not correctly displayed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#53]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Actions: select user -> select new OU -> "change" ->
Observation: OU field stays empty, only with coming back to user's profile the OU is correctly displayed
Expected Result: OU displayed right after "change"

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
