### ISSUE TITLE
Display role "Reporter" a a general role

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#54]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Current situation: If user assigns role reporter for a user, "reporter" is labeled for each OU, but in PubMan, it is actually a general role. 
If OU for user is changed, the Reporter role still displays the old  OU.

Question: Should the OU label be removed from role "reporter"?

**Comment by wilhelmfrank** [comment]
from 1.2.2 onward the REPORTER role has no target_id anymore.

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
