### ISSUE TITLE
Reset password for deactive user possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#55]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Actions: AdminTool: select deactivated user -> passwort "reset" -> new password given
qa-pure -> log in with new pass word -> no log in possible (which is correct)
AdminTool -> select user -> "Activate"
Observation: qa-pure -> log in with new pass word ->  log in possible 

Expected Result: passwort reset should not be possible for deactivated user

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok -> "reset" not available if user deactivated
