### ISSUE TITLE
Error message with changing password 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#56]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: chofmann

Actions: users -> enter new password -> "Change" ->

500, ERROR: {"timestamp":"2018-09-10T15:50:57.761","status":500,"error":"Internal Server Error","exception":"de.mpg.mpdl.inge.model.exception.IngeTechnicalException","message":"Could not update login, maybe key chofmann does not exist in table"}

**Comment by wilhelmfrank** [comment]
this is caused by bad data on qa.inge. All passwords are stored two times in the same table.

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok, user is able to change password now
