### ISSUE TITLE
Remove "close" in "create context form"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#57]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Current situation: create new context -> 
![grafik](https://user-images.githubusercontent.com/14921701/45301724-cd67bf00-b511-11e8-84d0-a975776faef3.png)

-> "close" leads to error message

Proposal: remove "close" since context is not yet opened

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
