### ISSUE TITLE
Add "confirm" after "delete" item

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#58]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.1. ALPHA
Test date: 10.09.2018
User: roland

Actions: OU/context/user -> "delete" 
Observation: item is removed immedeately

Suggestion: Insert a confirmation before item is finally removed

**Comment by wilhelmfrank** [comment]
fixed in 1.2.2

**Comment by hofmannc** [comment]
Testserver: qa.pure.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.2.2.
Test date: 12.09.2018
User: roland
result: ok
