### ISSUE TITLE
Enhancement: selected contect deleteble in field "add grants"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#6]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 26.10.2017
User: roland

Action:
User -> grants -> select „dep“ -> select context -> "add" -> delete entry in "add grants" -> select new context -> "add" -> earlier deleted context is displayed, too -> 

Observation: first entry not deletable in this field (only by "cancel").

Expected result: user is able to delete selected context in field "add grants"

**Comment by wilhelmfrank** [comment]
FIXED! Added function and button to clear selected grants.

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

ok
