### ISSUE TITLE
Typo:  OU "Alternative"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#9]
start page -> OU -> "+" -> 
![grafik](https://user-images.githubusercontent.com/14921701/32432497-27bf6b7e-c2d8-11e7-980f-81613944d1ac.png)

-> change to "alternative"

**Comment by wilhelmfrank** [comment]
FIXED

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland
ok
